spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flyway_prod
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password:
      initial-size: 5
      max-active: 20
      time-between-eviction-runs-millis: 100000
      min-evictable-idle-time-millis: 200000
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 10000
        config:
          enabled: true
        encoding:
          enabled: true
        wall:
          enabled: true
      stat-view-servlet:
        login-username: finup-funme-app-server
        login-password: finup-funme-app-server